// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/ThalesGroup/besec/api/models"
	"github.com/ThalesGroup/besec/lib"
)

// CreatePlanHandlerFunc turns a function with the right signature into a create plan handler
type CreatePlanHandlerFunc func(CreatePlanParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn CreatePlanHandlerFunc) Handle(params CreatePlanParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// CreatePlanHandler interface for that can handle valid create plan params
type CreatePlanHandler interface {
	Handle(CreatePlanParams, *models.User) middleware.Responder
}

// NewCreatePlan creates a new http.Handler for the create plan operation
func NewCreatePlan(ctx *middleware.Context, handler CreatePlanHandler) *CreatePlan {
	return &CreatePlan{Context: ctx, Handler: handler}
}

/* CreatePlan swagger:route POST /plan createPlan

CreatePlan create plan API

*/
type CreatePlan struct {
	Context *middleware.Context
	Handler CreatePlanHandler
}

func (o *CreatePlan) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCreatePlanParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// CreatePlanBody create plan body
//
// swagger:model CreatePlanBody
type CreatePlanBody struct {

	// details
	// Required: true
	Details *lib.PlanDetails `json:"details"`

	// responses
	// Required: true
	Responses *lib.PlanResponses `json:"responses"`
}

// Validate validates this create plan body
func (o *CreatePlanBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateDetails(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateResponses(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CreatePlanBody) validateDetails(formats strfmt.Registry) error {

	if err := validate.Required("body"+"."+"details", "body", o.Details); err != nil {
		return err
	}

	if o.Details != nil {
		if err := o.Details.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("body" + "." + "details")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("body" + "." + "details")
			}
			return err
		}
	}

	return nil
}

func (o *CreatePlanBody) validateResponses(formats strfmt.Registry) error {

	if err := validate.Required("body"+"."+"responses", "body", o.Responses); err != nil {
		return err
	}

	if o.Responses != nil {
		if err := o.Responses.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("body" + "." + "responses")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("body" + "." + "responses")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this create plan body based on the context it is used
func (o *CreatePlanBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateDetails(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateResponses(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CreatePlanBody) contextValidateDetails(ctx context.Context, formats strfmt.Registry) error {

	if o.Details != nil {
		if err := o.Details.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("body" + "." + "details")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("body" + "." + "details")
			}
			return err
		}
	}

	return nil
}

func (o *CreatePlanBody) contextValidateResponses(ctx context.Context, formats strfmt.Registry) error {

	if o.Responses != nil {
		if err := o.Responses.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("body" + "." + "responses")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("body" + "." + "responses")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *CreatePlanBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreatePlanBody) UnmarshalBinary(b []byte) error {
	var res CreatePlanBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// CreatePlanCreatedBody create plan created body
//
// swagger:model CreatePlanCreatedBody
type CreatePlanCreatedBody struct {

	// The ID of the plan
	// Required: true
	PlanID *string `json:"planId"`

	// The revision ID of the initial revision
	// Required: true
	RevisionID *string `json:"revisionId"`
}

// Validate validates this create plan created body
func (o *CreatePlanCreatedBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validatePlanID(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateRevisionID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CreatePlanCreatedBody) validatePlanID(formats strfmt.Registry) error {

	if err := validate.Required("createPlanCreated"+"."+"planId", "body", o.PlanID); err != nil {
		return err
	}

	return nil
}

func (o *CreatePlanCreatedBody) validateRevisionID(formats strfmt.Registry) error {

	if err := validate.Required("createPlanCreated"+"."+"revisionId", "body", o.RevisionID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this create plan created body based on context it is used
func (o *CreatePlanCreatedBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *CreatePlanCreatedBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreatePlanCreatedBody) UnmarshalBinary(b []byte) error {
	var res CreatePlanCreatedBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
