// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ThalesGroup/besec/api/models"
)

// CreatePlanRevisionOKCode is the HTTP code returned for type CreatePlanRevisionOK
const CreatePlanRevisionOKCode int = 200

/*CreatePlanRevisionOK OK

swagger:response createPlanRevisionOK
*/
type CreatePlanRevisionOK struct {

	/*The ID of the new revision
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewCreatePlanRevisionOK creates CreatePlanRevisionOK with default headers values
func NewCreatePlanRevisionOK() *CreatePlanRevisionOK {

	return &CreatePlanRevisionOK{}
}

// WithPayload adds the payload to the create plan revision o k response
func (o *CreatePlanRevisionOK) WithPayload(payload string) *CreatePlanRevisionOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create plan revision o k response
func (o *CreatePlanRevisionOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreatePlanRevisionOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*CreatePlanRevisionDefault error

swagger:response createPlanRevisionDefault
*/
type CreatePlanRevisionDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreatePlanRevisionDefault creates CreatePlanRevisionDefault with default headers values
func NewCreatePlanRevisionDefault(code int) *CreatePlanRevisionDefault {
	if code <= 0 {
		code = 500
	}

	return &CreatePlanRevisionDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the create plan revision default response
func (o *CreatePlanRevisionDefault) WithStatusCode(code int) *CreatePlanRevisionDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the create plan revision default response
func (o *CreatePlanRevisionDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the create plan revision default response
func (o *CreatePlanRevisionDefault) WithPayload(payload *models.Error) *CreatePlanRevisionDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create plan revision default response
func (o *CreatePlanRevisionDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreatePlanRevisionDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
