// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ThalesGroup/besec/api/models"
)

// DeletePlanNoContentCode is the HTTP code returned for type DeletePlanNoContent
const DeletePlanNoContentCode int = 204

/*DeletePlanNoContent Deleted

swagger:response deletePlanNoContent
*/
type DeletePlanNoContent struct {
}

// NewDeletePlanNoContent creates DeletePlanNoContent with default headers values
func NewDeletePlanNoContent() *DeletePlanNoContent {

	return &DeletePlanNoContent{}
}

// WriteResponse to the client
func (o *DeletePlanNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

/*DeletePlanDefault error

swagger:response deletePlanDefault
*/
type DeletePlanDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeletePlanDefault creates DeletePlanDefault with default headers values
func NewDeletePlanDefault(code int) *DeletePlanDefault {
	if code <= 0 {
		code = 500
	}

	return &DeletePlanDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete plan default response
func (o *DeletePlanDefault) WithStatusCode(code int) *DeletePlanDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete plan default response
func (o *DeletePlanDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete plan default response
func (o *DeletePlanDefault) WithPayload(payload *models.Error) *DeletePlanDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete plan default response
func (o *DeletePlanDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeletePlanDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
