// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ThalesGroup/besec/api/models"
)

// DeleteProjectNoContentCode is the HTTP code returned for type DeleteProjectNoContent
const DeleteProjectNoContentCode int = 204

/*DeleteProjectNoContent Deleted

swagger:response deleteProjectNoContent
*/
type DeleteProjectNoContent struct {
}

// NewDeleteProjectNoContent creates DeleteProjectNoContent with default headers values
func NewDeleteProjectNoContent() *DeleteProjectNoContent {

	return &DeleteProjectNoContent{}
}

// WriteResponse to the client
func (o *DeleteProjectNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

/*DeleteProjectDefault error

swagger:response deleteProjectDefault
*/
type DeleteProjectDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteProjectDefault creates DeleteProjectDefault with default headers values
func NewDeleteProjectDefault(code int) *DeleteProjectDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteProjectDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete project default response
func (o *DeleteProjectDefault) WithStatusCode(code int) *DeleteProjectDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete project default response
func (o *DeleteProjectDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete project default response
func (o *DeleteProjectDefault) WithPayload(payload *models.Error) *DeleteProjectDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete project default response
func (o *DeleteProjectDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteProjectDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
