// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/ThalesGroup/besec/api/models"
)

// DeletePlanHandlerFunc turns a function with the right signature into a delete plan handler
type DeletePlanHandlerFunc func(DeletePlanParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn DeletePlanHandlerFunc) Handle(params DeletePlanParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// DeletePlanHandler interface for that can handle valid delete plan params
type DeletePlanHandler interface {
	Handle(DeletePlanParams, *models.User) middleware.Responder
}

// NewDeletePlan creates a new http.Handler for the delete plan operation
func NewDeletePlan(ctx *middleware.Context, handler DeletePlanHandler) *DeletePlan {
	return &DeletePlan{Context: ctx, Handler: handler}
}

/* DeletePlan swagger:route DELETE /plan/{id} deletePlan

Delete this plan and all of the revisions associated with it

*/
type DeletePlan struct {
	Context *middleware.Context
	Handler DeletePlanHandler
}

func (o *DeletePlan) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeletePlanParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
