// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/ThalesGroup/besec/api/models"
)

// GetPracticesHandlerFunc turns a function with the right signature into a get practices handler
type GetPracticesHandlerFunc func(GetPracticesParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn GetPracticesHandlerFunc) Handle(params GetPracticesParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// GetPracticesHandler interface for that can handle valid get practices params
type GetPracticesHandler interface {
	Handle(GetPracticesParams, *models.User) middleware.Responder
}

// NewGetPractices creates a new http.Handler for the get practices operation
func NewGetPractices(ctx *middleware.Context, handler GetPracticesHandler) *GetPractices {
	return &GetPractices{Context: ctx, Handler: handler}
}

/* GetPractices swagger:route GET /practices/{version} getPractices

GetPractices get practices API

*/
type GetPractices struct {
	Context *middleware.Context
	Handler GetPracticesHandler
}

func (o *GetPractices) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetPracticesParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
