// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewGetPracticesParams creates a new GetPracticesParams object
//
// There are no default values defined in the spec.
func NewGetPracticesParams() GetPracticesParams {

	return GetPracticesParams{}
}

// GetPracticesParams contains all the bound params for the get practices operation
// typically these are obtained from a http.Request
//
// swagger:parameters getPractices
type GetPracticesParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The version, or the special value "latest".
	  Required: true
	  In: path
	*/
	Version string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetPracticesParams() beforehand.
func (o *GetPracticesParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rVersion, rhkVersion, _ := route.Params.GetOK("version")
	if err := o.bindVersion(rVersion, rhkVersion, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindVersion binds and validates parameter Version from path.
func (o *GetPracticesParams) bindVersion(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.Version = raw

	return nil
}
