// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ThalesGroup/besec/api/models"
)

// GetPlanVersionsOKCode is the HTTP code returned for type GetPlanVersionsOK
const GetPlanVersionsOKCode int = 200

/*GetPlanVersionsOK OK

swagger:response getPlanVersionsOK
*/
type GetPlanVersionsOK struct {

	/*all of the versions for this plan, in order from oldest to latest
	  In: Body
	*/
	Payload []*models.RevisionVersion `json:"body,omitempty"`
}

// NewGetPlanVersionsOK creates GetPlanVersionsOK with default headers values
func NewGetPlanVersionsOK() *GetPlanVersionsOK {

	return &GetPlanVersionsOK{}
}

// WithPayload adds the payload to the get plan versions o k response
func (o *GetPlanVersionsOK) WithPayload(payload []*models.RevisionVersion) *GetPlanVersionsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get plan versions o k response
func (o *GetPlanVersionsOK) SetPayload(payload []*models.RevisionVersion) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPlanVersionsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.RevisionVersion, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*GetPlanVersionsDefault error

swagger:response getPlanVersionsDefault
*/
type GetPlanVersionsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetPlanVersionsDefault creates GetPlanVersionsDefault with default headers values
func NewGetPlanVersionsDefault(code int) *GetPlanVersionsDefault {
	if code <= 0 {
		code = 500
	}

	return &GetPlanVersionsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get plan versions default response
func (o *GetPlanVersionsDefault) WithStatusCode(code int) *GetPlanVersionsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get plan versions default response
func (o *GetPlanVersionsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get plan versions default response
func (o *GetPlanVersionsDefault) WithPayload(payload *models.Error) *GetPlanVersionsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get plan versions default response
func (o *GetPlanVersionsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPlanVersionsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
