// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/ThalesGroup/besec/api/models"
)

// GetPlanVersionsHandlerFunc turns a function with the right signature into a get plan versions handler
type GetPlanVersionsHandlerFunc func(GetPlanVersionsParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn GetPlanVersionsHandlerFunc) Handle(params GetPlanVersionsParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// GetPlanVersionsHandler interface for that can handle valid get plan versions params
type GetPlanVersionsHandler interface {
	Handle(GetPlanVersionsParams, *models.User) middleware.Responder
}

// NewGetPlanVersions creates a new http.Handler for the get plan versions operation
func NewGetPlanVersions(ctx *middleware.Context, handler GetPlanVersionsHandler) *GetPlanVersions {
	return &GetPlanVersions{Context: ctx, Handler: handler}
}

/* GetPlanVersions swagger:route GET /plan/{id}/versions getPlanVersions

GetPlanVersions get plan versions API

*/
type GetPlanVersions struct {
	Context *middleware.Context
	Handler GetPlanVersionsHandler
}

func (o *GetPlanVersions) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetPlanVersionsParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
