// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/ThalesGroup/besec/api/models"
)

// GetPlanRevisionHandlerFunc turns a function with the right signature into a get plan revision handler
type GetPlanRevisionHandlerFunc func(GetPlanRevisionParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn GetPlanRevisionHandlerFunc) Handle(params GetPlanRevisionParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// GetPlanRevisionHandler interface for that can handle valid get plan revision params
type GetPlanRevisionHandler interface {
	Handle(GetPlanRevisionParams, *models.User) middleware.Responder
}

// NewGetPlanRevision creates a new http.Handler for the get plan revision operation
func NewGetPlanRevision(ctx *middleware.Context, handler GetPlanRevisionHandler) *GetPlanRevision {
	return &GetPlanRevision{Context: ctx, Handler: handler}
}

/* GetPlanRevision swagger:route GET /plan/{id}/revision/{revId} getPlanRevision

GetPlanRevision get plan revision API

*/
type GetPlanRevision struct {
	Context *middleware.Context
	Handler GetPlanRevisionHandler
}

func (o *GetPlanRevision) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetPlanRevisionParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
