// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ThalesGroup/besec/api/models"
	"github.com/ThalesGroup/besec/lib"
)

// GetPlanRevisionOKCode is the HTTP code returned for type GetPlanRevisionOK
const GetPlanRevisionOKCode int = 200

/*GetPlanRevisionOK OK

swagger:response getPlanRevisionOK
*/
type GetPlanRevisionOK struct {

	/*
	  In: Body
	*/
	Payload *lib.PlanDetails `json:"body,omitempty"`
}

// NewGetPlanRevisionOK creates GetPlanRevisionOK with default headers values
func NewGetPlanRevisionOK() *GetPlanRevisionOK {

	return &GetPlanRevisionOK{}
}

// WithPayload adds the payload to the get plan revision o k response
func (o *GetPlanRevisionOK) WithPayload(payload *lib.PlanDetails) *GetPlanRevisionOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get plan revision o k response
func (o *GetPlanRevisionOK) SetPayload(payload *lib.PlanDetails) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPlanRevisionOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetPlanRevisionDefault error

swagger:response getPlanRevisionDefault
*/
type GetPlanRevisionDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetPlanRevisionDefault creates GetPlanRevisionDefault with default headers values
func NewGetPlanRevisionDefault(code int) *GetPlanRevisionDefault {
	if code <= 0 {
		code = 500
	}

	return &GetPlanRevisionDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get plan revision default response
func (o *GetPlanRevisionDefault) WithStatusCode(code int) *GetPlanRevisionDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get plan revision default response
func (o *GetPlanRevisionDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get plan revision default response
func (o *GetPlanRevisionDefault) WithPayload(payload *models.Error) *GetPlanRevisionDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get plan revision default response
func (o *GetPlanRevisionDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPlanRevisionDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
