// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ThalesGroup/besec/api/models"
)

// GetAuthConfigOKCode is the HTTP code returned for type GetAuthConfigOK
const GetAuthConfigOKCode int = 200

/*GetAuthConfigOK OK

swagger:response getAuthConfigOK
*/
type GetAuthConfigOK struct {

	/*
	  In: Body
	*/
	Payload *models.AuthConfig `json:"body,omitempty"`
}

// NewGetAuthConfigOK creates GetAuthConfigOK with default headers values
func NewGetAuthConfigOK() *GetAuthConfigOK {

	return &GetAuthConfigOK{}
}

// WithPayload adds the payload to the get auth config o k response
func (o *GetAuthConfigOK) WithPayload(payload *models.AuthConfig) *GetAuthConfigOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get auth config o k response
func (o *GetAuthConfigOK) SetPayload(payload *models.AuthConfig) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAuthConfigOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetAuthConfigDefault error

swagger:response getAuthConfigDefault
*/
type GetAuthConfigDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAuthConfigDefault creates GetAuthConfigDefault with default headers values
func NewGetAuthConfigDefault(code int) *GetAuthConfigDefault {
	if code <= 0 {
		code = 500
	}

	return &GetAuthConfigDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get auth config default response
func (o *GetAuthConfigDefault) WithStatusCode(code int) *GetAuthConfigDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get auth config default response
func (o *GetAuthConfigDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get auth config default response
func (o *GetAuthConfigDefault) WithPayload(payload *models.Error) *GetAuthConfigDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get auth config default response
func (o *GetAuthConfigDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAuthConfigDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
