// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetAuthConfigHandlerFunc turns a function with the right signature into a get auth config handler
type GetAuthConfigHandlerFunc func(GetAuthConfigParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAuthConfigHandlerFunc) Handle(params GetAuthConfigParams) middleware.Responder {
	return fn(params)
}

// GetAuthConfigHandler interface for that can handle valid get auth config params
type GetAuthConfigHandler interface {
	Handle(GetAuthConfigParams) middleware.Responder
}

// NewGetAuthConfig creates a new http.Handler for the get auth config operation
func NewGetAuthConfig(ctx *middleware.Context, handler GetAuthConfigHandler) *GetAuthConfig {
	return &GetAuthConfig{Context: ctx, Handler: handler}
}

/* GetAuthConfig swagger:route GET /auth getAuthConfig

GetAuthConfig get auth config API

*/
type GetAuthConfig struct {
	Context *middleware.Context
	Handler GetAuthConfigHandler
}

func (o *GetAuthConfig) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetAuthConfigParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
