// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
)

// NewGetAuthConfigParams creates a new GetAuthConfigParams object
//
// There are no default values defined in the spec.
func NewGetAuthConfigParams() GetAuthConfigParams {

	return GetAuthConfigParams{}
}

// GetAuthConfigParams contains all the bound params for the get auth config operation
// typically these are obtained from a http.Request
//
// swagger:parameters getAuthConfig
type GetAuthConfigParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetAuthConfigParams() beforehand.
func (o *GetAuthConfigParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
