// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/ThalesGroup/besec/api/models"
)

// ListProjectsHandlerFunc turns a function with the right signature into a list projects handler
type ListProjectsHandlerFunc func(ListProjectsParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn ListProjectsHandlerFunc) Handle(params ListProjectsParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// ListProjectsHandler interface for that can handle valid list projects params
type ListProjectsHandler interface {
	Handle(ListProjectsParams, *models.User) middleware.Responder
}

// NewListProjects creates a new http.Handler for the list projects operation
func NewListProjects(ctx *middleware.Context, handler ListProjectsHandler) *ListProjects {
	return &ListProjects{Context: ctx, Handler: handler}
}

/* ListProjects swagger:route GET /project listProjects

ListProjects list projects API

*/
type ListProjects struct {
	Context *middleware.Context
	Handler ListProjectsHandler
}

func (o *ListProjects) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewListProjectsParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
