// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ThalesGroup/besec/api/models"
)

// ListProjectsOKCode is the HTTP code returned for type ListProjectsOK
const ListProjectsOKCode int = 200

/*ListProjectsOK OK

swagger:response listProjectsOK
*/
type ListProjectsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Project `json:"body,omitempty"`
}

// NewListProjectsOK creates ListProjectsOK with default headers values
func NewListProjectsOK() *ListProjectsOK {

	return &ListProjectsOK{}
}

// WithPayload adds the payload to the list projects o k response
func (o *ListProjectsOK) WithPayload(payload []*models.Project) *ListProjectsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list projects o k response
func (o *ListProjectsOK) SetPayload(payload []*models.Project) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListProjectsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Project, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*ListProjectsDefault error

swagger:response listProjectsDefault
*/
type ListProjectsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListProjectsDefault creates ListProjectsDefault with default headers values
func NewListProjectsDefault(code int) *ListProjectsDefault {
	if code <= 0 {
		code = 500
	}

	return &ListProjectsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the list projects default response
func (o *ListProjectsDefault) WithStatusCode(code int) *ListProjectsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the list projects default response
func (o *ListProjectsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the list projects default response
func (o *ListProjectsDefault) WithPayload(payload *models.Error) *ListProjectsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list projects default response
func (o *ListProjectsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListProjectsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
