// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/ThalesGroup/besec/api/models"
)

// ListPracticesVersionsHandlerFunc turns a function with the right signature into a list practices versions handler
type ListPracticesVersionsHandlerFunc func(ListPracticesVersionsParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn ListPracticesVersionsHandlerFunc) Handle(params ListPracticesVersionsParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// ListPracticesVersionsHandler interface for that can handle valid list practices versions params
type ListPracticesVersionsHandler interface {
	Handle(ListPracticesVersionsParams, *models.User) middleware.Responder
}

// NewListPracticesVersions creates a new http.Handler for the list practices versions operation
func NewListPracticesVersions(ctx *middleware.Context, handler ListPracticesVersionsHandler) *ListPracticesVersions {
	return &ListPracticesVersions{Context: ctx, Handler: handler}
}

/* ListPracticesVersions swagger:route GET /practices listPracticesVersions

ListPracticesVersions list practices versions API

*/
type ListPracticesVersions struct {
	Context *middleware.Context
	Handler ListPracticesVersionsHandler
}

func (o *ListPracticesVersions) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewListPracticesVersionsParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
