// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ThalesGroup/besec/api/models"
)

// ListPracticesVersionsOKCode is the HTTP code returned for type ListPracticesVersionsOK
const ListPracticesVersionsOKCode int = 200

/*ListPracticesVersionsOK OK

swagger:response listPracticesVersionsOK
*/
type ListPracticesVersionsOK struct {

	/*All of the versions, from oldest to newest
	  In: Body
	*/
	Payload []string `json:"body,omitempty"`
}

// NewListPracticesVersionsOK creates ListPracticesVersionsOK with default headers values
func NewListPracticesVersionsOK() *ListPracticesVersionsOK {

	return &ListPracticesVersionsOK{}
}

// WithPayload adds the payload to the list practices versions o k response
func (o *ListPracticesVersionsOK) WithPayload(payload []string) *ListPracticesVersionsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list practices versions o k response
func (o *ListPracticesVersionsOK) SetPayload(payload []string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListPracticesVersionsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]string, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*ListPracticesVersionsDefault error

swagger:response listPracticesVersionsDefault
*/
type ListPracticesVersionsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListPracticesVersionsDefault creates ListPracticesVersionsDefault with default headers values
func NewListPracticesVersionsDefault(code int) *ListPracticesVersionsDefault {
	if code <= 0 {
		code = 500
	}

	return &ListPracticesVersionsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the list practices versions default response
func (o *ListPracticesVersionsDefault) WithStatusCode(code int) *ListPracticesVersionsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the list practices versions default response
func (o *ListPracticesVersionsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the list practices versions default response
func (o *ListPracticesVersionsDefault) WithPayload(payload *models.Error) *ListPracticesVersionsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list practices versions default response
func (o *ListPracticesVersionsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListPracticesVersionsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
