// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/ThalesGroup/besec/api/models"
)

// LoggedInHandlerFunc turns a function with the right signature into a logged in handler
type LoggedInHandlerFunc func(LoggedInParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn LoggedInHandlerFunc) Handle(params LoggedInParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// LoggedInHandler interface for that can handle valid logged in params
type LoggedInHandler interface {
	Handle(LoggedInParams, *models.User) middleware.Responder
}

// NewLoggedIn creates a new http.Handler for the logged in operation
func NewLoggedIn(ctx *middleware.Context, handler LoggedInHandler) *LoggedIn {
	return &LoggedIn{Context: ctx, Handler: handler}
}

/* LoggedIn swagger:route POST /auth loggedIn

Used to trigger one-time events like requesting access. Clients should hit this once after obtaining an ID token, and can use or ignore the response.

*/
type LoggedIn struct {
	Context *middleware.Context
	Handler LoggedInHandler
}

func (o *LoggedIn) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewLoggedInParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
