// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCreatePlanRevisionParams creates a new CreatePlanRevisionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreatePlanRevisionParams() *CreatePlanRevisionParams {
	return &CreatePlanRevisionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreatePlanRevisionParamsWithTimeout creates a new CreatePlanRevisionParams object
// with the ability to set a timeout on a request.
func NewCreatePlanRevisionParamsWithTimeout(timeout time.Duration) *CreatePlanRevisionParams {
	return &CreatePlanRevisionParams{
		timeout: timeout,
	}
}

// NewCreatePlanRevisionParamsWithContext creates a new CreatePlanRevisionParams object
// with the ability to set a context for a request.
func NewCreatePlanRevisionParamsWithContext(ctx context.Context) *CreatePlanRevisionParams {
	return &CreatePlanRevisionParams{
		Context: ctx,
	}
}

// NewCreatePlanRevisionParamsWithHTTPClient creates a new CreatePlanRevisionParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreatePlanRevisionParamsWithHTTPClient(client *http.Client) *CreatePlanRevisionParams {
	return &CreatePlanRevisionParams{
		HTTPClient: client,
	}
}

/* CreatePlanRevisionParams contains all the parameters to send to the API endpoint
   for the create plan revision operation.

   Typically these are written to a http.Request.
*/
type CreatePlanRevisionParams struct {

	// Body.
	Body CreatePlanRevisionBody

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create plan revision params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreatePlanRevisionParams) WithDefaults() *CreatePlanRevisionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create plan revision params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreatePlanRevisionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create plan revision params
func (o *CreatePlanRevisionParams) WithTimeout(timeout time.Duration) *CreatePlanRevisionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create plan revision params
func (o *CreatePlanRevisionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create plan revision params
func (o *CreatePlanRevisionParams) WithContext(ctx context.Context) *CreatePlanRevisionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create plan revision params
func (o *CreatePlanRevisionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create plan revision params
func (o *CreatePlanRevisionParams) WithHTTPClient(client *http.Client) *CreatePlanRevisionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create plan revision params
func (o *CreatePlanRevisionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create plan revision params
func (o *CreatePlanRevisionParams) WithBody(body CreatePlanRevisionBody) *CreatePlanRevisionParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create plan revision params
func (o *CreatePlanRevisionParams) SetBody(body CreatePlanRevisionBody) {
	o.Body = body
}

// WithID adds the id to the create plan revision params
func (o *CreatePlanRevisionParams) WithID(id string) *CreatePlanRevisionParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the create plan revision params
func (o *CreatePlanRevisionParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *CreatePlanRevisionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
