// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ThalesGroup/besec/api/models"
)

// DeletePlanReader is a Reader for the DeletePlan structure.
type DeletePlanReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeletePlanReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeletePlanNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDeletePlanDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeletePlanNoContent creates a DeletePlanNoContent with default headers values
func NewDeletePlanNoContent() *DeletePlanNoContent {
	return &DeletePlanNoContent{}
}

/* DeletePlanNoContent describes a response with status code 204, with default header values.

Deleted
*/
type DeletePlanNoContent struct {
}

func (o *DeletePlanNoContent) Error() string {
	return fmt.Sprintf("[DELETE /plan/{id}][%d] deletePlanNoContent ", 204)
}

func (o *DeletePlanNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeletePlanDefault creates a DeletePlanDefault with default headers values
func NewDeletePlanDefault(code int) *DeletePlanDefault {
	return &DeletePlanDefault{
		_statusCode: code,
	}
}

/* DeletePlanDefault describes a response with status code -1, with default header values.

error
*/
type DeletePlanDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the delete plan default response
func (o *DeletePlanDefault) Code() int {
	return o._statusCode
}

func (o *DeletePlanDefault) Error() string {
	return fmt.Sprintf("[DELETE /plan/{id}][%d] deletePlan default  %+v", o._statusCode, o.Payload)
}
func (o *DeletePlanDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeletePlanDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
