// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetPlanRevisionPracticeResponsesParams creates a new GetPlanRevisionPracticeResponsesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetPlanRevisionPracticeResponsesParams() *GetPlanRevisionPracticeResponsesParams {
	return &GetPlanRevisionPracticeResponsesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetPlanRevisionPracticeResponsesParamsWithTimeout creates a new GetPlanRevisionPracticeResponsesParams object
// with the ability to set a timeout on a request.
func NewGetPlanRevisionPracticeResponsesParamsWithTimeout(timeout time.Duration) *GetPlanRevisionPracticeResponsesParams {
	return &GetPlanRevisionPracticeResponsesParams{
		timeout: timeout,
	}
}

// NewGetPlanRevisionPracticeResponsesParamsWithContext creates a new GetPlanRevisionPracticeResponsesParams object
// with the ability to set a context for a request.
func NewGetPlanRevisionPracticeResponsesParamsWithContext(ctx context.Context) *GetPlanRevisionPracticeResponsesParams {
	return &GetPlanRevisionPracticeResponsesParams{
		Context: ctx,
	}
}

// NewGetPlanRevisionPracticeResponsesParamsWithHTTPClient creates a new GetPlanRevisionPracticeResponsesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetPlanRevisionPracticeResponsesParamsWithHTTPClient(client *http.Client) *GetPlanRevisionPracticeResponsesParams {
	return &GetPlanRevisionPracticeResponsesParams{
		HTTPClient: client,
	}
}

/* GetPlanRevisionPracticeResponsesParams contains all the parameters to send to the API endpoint
   for the get plan revision practice responses operation.

   Typically these are written to a http.Request.
*/
type GetPlanRevisionPracticeResponsesParams struct {

	// ID.
	ID string

	// RevID.
	RevID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get plan revision practice responses params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPlanRevisionPracticeResponsesParams) WithDefaults() *GetPlanRevisionPracticeResponsesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get plan revision practice responses params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPlanRevisionPracticeResponsesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get plan revision practice responses params
func (o *GetPlanRevisionPracticeResponsesParams) WithTimeout(timeout time.Duration) *GetPlanRevisionPracticeResponsesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get plan revision practice responses params
func (o *GetPlanRevisionPracticeResponsesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get plan revision practice responses params
func (o *GetPlanRevisionPracticeResponsesParams) WithContext(ctx context.Context) *GetPlanRevisionPracticeResponsesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get plan revision practice responses params
func (o *GetPlanRevisionPracticeResponsesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get plan revision practice responses params
func (o *GetPlanRevisionPracticeResponsesParams) WithHTTPClient(client *http.Client) *GetPlanRevisionPracticeResponsesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get plan revision practice responses params
func (o *GetPlanRevisionPracticeResponsesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get plan revision practice responses params
func (o *GetPlanRevisionPracticeResponsesParams) WithID(id string) *GetPlanRevisionPracticeResponsesParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get plan revision practice responses params
func (o *GetPlanRevisionPracticeResponsesParams) SetID(id string) {
	o.ID = id
}

// WithRevID adds the revID to the get plan revision practice responses params
func (o *GetPlanRevisionPracticeResponsesParams) WithRevID(revID string) *GetPlanRevisionPracticeResponsesParams {
	o.SetRevID(revID)
	return o
}

// SetRevID adds the revId to the get plan revision practice responses params
func (o *GetPlanRevisionPracticeResponsesParams) SetRevID(revID string) {
	o.RevID = revID
}

// WriteToRequest writes these params to a swagger request
func (o *GetPlanRevisionPracticeResponsesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param revId
	if err := r.SetPathParam("revId", o.RevID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
