// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ThalesGroup/besec/api/models"
)

// GetAuthConfigReader is a Reader for the GetAuthConfig structure.
type GetAuthConfigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAuthConfigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAuthConfigOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetAuthConfigDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetAuthConfigOK creates a GetAuthConfigOK with default headers values
func NewGetAuthConfigOK() *GetAuthConfigOK {
	return &GetAuthConfigOK{}
}

/* GetAuthConfigOK describes a response with status code 200, with default header values.

OK
*/
type GetAuthConfigOK struct {
	Payload *models.AuthConfig
}

func (o *GetAuthConfigOK) Error() string {
	return fmt.Sprintf("[GET /auth][%d] getAuthConfigOK  %+v", 200, o.Payload)
}
func (o *GetAuthConfigOK) GetPayload() *models.AuthConfig {
	return o.Payload
}

func (o *GetAuthConfigOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AuthConfig)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAuthConfigDefault creates a GetAuthConfigDefault with default headers values
func NewGetAuthConfigDefault(code int) *GetAuthConfigDefault {
	return &GetAuthConfigDefault{
		_statusCode: code,
	}
}

/* GetAuthConfigDefault describes a response with status code -1, with default header values.

error
*/
type GetAuthConfigDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get auth config default response
func (o *GetAuthConfigDefault) Code() int {
	return o._statusCode
}

func (o *GetAuthConfigDefault) Error() string {
	return fmt.Sprintf("[GET /auth][%d] getAuthConfig default  %+v", o._statusCode, o.Payload)
}
func (o *GetAuthConfigDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetAuthConfigDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
