// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetPlanVersionsParams creates a new GetPlanVersionsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetPlanVersionsParams() *GetPlanVersionsParams {
	return &GetPlanVersionsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetPlanVersionsParamsWithTimeout creates a new GetPlanVersionsParams object
// with the ability to set a timeout on a request.
func NewGetPlanVersionsParamsWithTimeout(timeout time.Duration) *GetPlanVersionsParams {
	return &GetPlanVersionsParams{
		timeout: timeout,
	}
}

// NewGetPlanVersionsParamsWithContext creates a new GetPlanVersionsParams object
// with the ability to set a context for a request.
func NewGetPlanVersionsParamsWithContext(ctx context.Context) *GetPlanVersionsParams {
	return &GetPlanVersionsParams{
		Context: ctx,
	}
}

// NewGetPlanVersionsParamsWithHTTPClient creates a new GetPlanVersionsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetPlanVersionsParamsWithHTTPClient(client *http.Client) *GetPlanVersionsParams {
	return &GetPlanVersionsParams{
		HTTPClient: client,
	}
}

/* GetPlanVersionsParams contains all the parameters to send to the API endpoint
   for the get plan versions operation.

   Typically these are written to a http.Request.
*/
type GetPlanVersionsParams struct {

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get plan versions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPlanVersionsParams) WithDefaults() *GetPlanVersionsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get plan versions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPlanVersionsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get plan versions params
func (o *GetPlanVersionsParams) WithTimeout(timeout time.Duration) *GetPlanVersionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get plan versions params
func (o *GetPlanVersionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get plan versions params
func (o *GetPlanVersionsParams) WithContext(ctx context.Context) *GetPlanVersionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get plan versions params
func (o *GetPlanVersionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get plan versions params
func (o *GetPlanVersionsParams) WithHTTPClient(client *http.Client) *GetPlanVersionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get plan versions params
func (o *GetPlanVersionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get plan versions params
func (o *GetPlanVersionsParams) WithID(id string) *GetPlanVersionsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get plan versions params
func (o *GetPlanVersionsParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetPlanVersionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
