// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetPracticesParams creates a new GetPracticesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetPracticesParams() *GetPracticesParams {
	return &GetPracticesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetPracticesParamsWithTimeout creates a new GetPracticesParams object
// with the ability to set a timeout on a request.
func NewGetPracticesParamsWithTimeout(timeout time.Duration) *GetPracticesParams {
	return &GetPracticesParams{
		timeout: timeout,
	}
}

// NewGetPracticesParamsWithContext creates a new GetPracticesParams object
// with the ability to set a context for a request.
func NewGetPracticesParamsWithContext(ctx context.Context) *GetPracticesParams {
	return &GetPracticesParams{
		Context: ctx,
	}
}

// NewGetPracticesParamsWithHTTPClient creates a new GetPracticesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetPracticesParamsWithHTTPClient(client *http.Client) *GetPracticesParams {
	return &GetPracticesParams{
		HTTPClient: client,
	}
}

/* GetPracticesParams contains all the parameters to send to the API endpoint
   for the get practices operation.

   Typically these are written to a http.Request.
*/
type GetPracticesParams struct {

	/* Version.

	   The version, or the special value "latest".
	*/
	Version string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get practices params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPracticesParams) WithDefaults() *GetPracticesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get practices params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPracticesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get practices params
func (o *GetPracticesParams) WithTimeout(timeout time.Duration) *GetPracticesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get practices params
func (o *GetPracticesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get practices params
func (o *GetPracticesParams) WithContext(ctx context.Context) *GetPracticesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get practices params
func (o *GetPracticesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get practices params
func (o *GetPracticesParams) WithHTTPClient(client *http.Client) *GetPracticesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get practices params
func (o *GetPracticesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithVersion adds the version to the get practices params
func (o *GetPracticesParams) WithVersion(version string) *GetPracticesParams {
	o.SetVersion(version)
	return o
}

// SetVersion adds the version to the get practices params
func (o *GetPracticesParams) SetVersion(version string) {
	o.Version = version
}

// WriteToRequest writes these params to a swagger request
func (o *GetPracticesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param version
	if err := r.SetPathParam("version", o.Version); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
