// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ThalesGroup/besec/api/models"
	"github.com/ThalesGroup/besec/lib"
)

// GetPlanRevisionReader is a Reader for the GetPlanRevision structure.
type GetPlanRevisionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPlanRevisionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPlanRevisionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetPlanRevisionDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetPlanRevisionOK creates a GetPlanRevisionOK with default headers values
func NewGetPlanRevisionOK() *GetPlanRevisionOK {
	return &GetPlanRevisionOK{}
}

/* GetPlanRevisionOK describes a response with status code 200, with default header values.

OK
*/
type GetPlanRevisionOK struct {
	Payload *lib.PlanDetails
}

func (o *GetPlanRevisionOK) Error() string {
	return fmt.Sprintf("[GET /plan/{id}/revision/{revId}][%d] getPlanRevisionOK  %+v", 200, o.Payload)
}
func (o *GetPlanRevisionOK) GetPayload() *lib.PlanDetails {
	return o.Payload
}

func (o *GetPlanRevisionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(lib.PlanDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPlanRevisionDefault creates a GetPlanRevisionDefault with default headers values
func NewGetPlanRevisionDefault(code int) *GetPlanRevisionDefault {
	return &GetPlanRevisionDefault{
		_statusCode: code,
	}
}

/* GetPlanRevisionDefault describes a response with status code -1, with default header values.

error
*/
type GetPlanRevisionDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get plan revision default response
func (o *GetPlanRevisionDefault) Code() int {
	return o._statusCode
}

func (o *GetPlanRevisionDefault) Error() string {
	return fmt.Sprintf("[GET /plan/{id}/revision/{revId}][%d] getPlanRevision default  %+v", o._statusCode, o.Payload)
}
func (o *GetPlanRevisionDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetPlanRevisionDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
