// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAuthConfigParams creates a new GetAuthConfigParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAuthConfigParams() *GetAuthConfigParams {
	return &GetAuthConfigParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAuthConfigParamsWithTimeout creates a new GetAuthConfigParams object
// with the ability to set a timeout on a request.
func NewGetAuthConfigParamsWithTimeout(timeout time.Duration) *GetAuthConfigParams {
	return &GetAuthConfigParams{
		timeout: timeout,
	}
}

// NewGetAuthConfigParamsWithContext creates a new GetAuthConfigParams object
// with the ability to set a context for a request.
func NewGetAuthConfigParamsWithContext(ctx context.Context) *GetAuthConfigParams {
	return &GetAuthConfigParams{
		Context: ctx,
	}
}

// NewGetAuthConfigParamsWithHTTPClient creates a new GetAuthConfigParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAuthConfigParamsWithHTTPClient(client *http.Client) *GetAuthConfigParams {
	return &GetAuthConfigParams{
		HTTPClient: client,
	}
}

/* GetAuthConfigParams contains all the parameters to send to the API endpoint
   for the get auth config operation.

   Typically these are written to a http.Request.
*/
type GetAuthConfigParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get auth config params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAuthConfigParams) WithDefaults() *GetAuthConfigParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get auth config params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAuthConfigParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get auth config params
func (o *GetAuthConfigParams) WithTimeout(timeout time.Duration) *GetAuthConfigParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get auth config params
func (o *GetAuthConfigParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get auth config params
func (o *GetAuthConfigParams) WithContext(ctx context.Context) *GetAuthConfigParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get auth config params
func (o *GetAuthConfigParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get auth config params
func (o *GetAuthConfigParams) WithHTTPClient(client *http.Client) *GetAuthConfigParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get auth config params
func (o *GetAuthConfigParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAuthConfigParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
