// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetPlanRevisionParams creates a new GetPlanRevisionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetPlanRevisionParams() *GetPlanRevisionParams {
	return &GetPlanRevisionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetPlanRevisionParamsWithTimeout creates a new GetPlanRevisionParams object
// with the ability to set a timeout on a request.
func NewGetPlanRevisionParamsWithTimeout(timeout time.Duration) *GetPlanRevisionParams {
	return &GetPlanRevisionParams{
		timeout: timeout,
	}
}

// NewGetPlanRevisionParamsWithContext creates a new GetPlanRevisionParams object
// with the ability to set a context for a request.
func NewGetPlanRevisionParamsWithContext(ctx context.Context) *GetPlanRevisionParams {
	return &GetPlanRevisionParams{
		Context: ctx,
	}
}

// NewGetPlanRevisionParamsWithHTTPClient creates a new GetPlanRevisionParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetPlanRevisionParamsWithHTTPClient(client *http.Client) *GetPlanRevisionParams {
	return &GetPlanRevisionParams{
		HTTPClient: client,
	}
}

/* GetPlanRevisionParams contains all the parameters to send to the API endpoint
   for the get plan revision operation.

   Typically these are written to a http.Request.
*/
type GetPlanRevisionParams struct {

	// ID.
	ID string

	// RevID.
	RevID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get plan revision params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPlanRevisionParams) WithDefaults() *GetPlanRevisionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get plan revision params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPlanRevisionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get plan revision params
func (o *GetPlanRevisionParams) WithTimeout(timeout time.Duration) *GetPlanRevisionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get plan revision params
func (o *GetPlanRevisionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get plan revision params
func (o *GetPlanRevisionParams) WithContext(ctx context.Context) *GetPlanRevisionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get plan revision params
func (o *GetPlanRevisionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get plan revision params
func (o *GetPlanRevisionParams) WithHTTPClient(client *http.Client) *GetPlanRevisionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get plan revision params
func (o *GetPlanRevisionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get plan revision params
func (o *GetPlanRevisionParams) WithID(id string) *GetPlanRevisionParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get plan revision params
func (o *GetPlanRevisionParams) SetID(id string) {
	o.ID = id
}

// WithRevID adds the revID to the get plan revision params
func (o *GetPlanRevisionParams) WithRevID(revID string) *GetPlanRevisionParams {
	o.SetRevID(revID)
	return o
}

// SetRevID adds the revId to the get plan revision params
func (o *GetPlanRevisionParams) SetRevID(revID string) {
	o.RevID = revID
}

// WriteToRequest writes these params to a swagger request
func (o *GetPlanRevisionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param revId
	if err := r.SetPathParam("revId", o.RevID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
