// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ThalesGroup/besec/api/models"
	"github.com/ThalesGroup/besec/lib"
)

// GetPlanRevisionPracticeResponsesReader is a Reader for the GetPlanRevisionPracticeResponses structure.
type GetPlanRevisionPracticeResponsesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPlanRevisionPracticeResponsesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPlanRevisionPracticeResponsesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetPlanRevisionPracticeResponsesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetPlanRevisionPracticeResponsesOK creates a GetPlanRevisionPracticeResponsesOK with default headers values
func NewGetPlanRevisionPracticeResponsesOK() *GetPlanRevisionPracticeResponsesOK {
	return &GetPlanRevisionPracticeResponsesOK{}
}

/* GetPlanRevisionPracticeResponsesOK describes a response with status code 200, with default header values.

OK
*/
type GetPlanRevisionPracticeResponsesOK struct {
	Payload *lib.PlanResponses
}

func (o *GetPlanRevisionPracticeResponsesOK) Error() string {
	return fmt.Sprintf("[GET /plan/{id}/revision/{revId}/responses][%d] getPlanRevisionPracticeResponsesOK  %+v", 200, o.Payload)
}
func (o *GetPlanRevisionPracticeResponsesOK) GetPayload() *lib.PlanResponses {
	return o.Payload
}

func (o *GetPlanRevisionPracticeResponsesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(lib.PlanResponses)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPlanRevisionPracticeResponsesDefault creates a GetPlanRevisionPracticeResponsesDefault with default headers values
func NewGetPlanRevisionPracticeResponsesDefault(code int) *GetPlanRevisionPracticeResponsesDefault {
	return &GetPlanRevisionPracticeResponsesDefault{
		_statusCode: code,
	}
}

/* GetPlanRevisionPracticeResponsesDefault describes a response with status code -1, with default header values.

error
*/
type GetPlanRevisionPracticeResponsesDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get plan revision practice responses default response
func (o *GetPlanRevisionPracticeResponsesDefault) Code() int {
	return o._statusCode
}

func (o *GetPlanRevisionPracticeResponsesDefault) Error() string {
	return fmt.Sprintf("[GET /plan/{id}/revision/{revId}/responses][%d] getPlanRevisionPracticeResponses default  %+v", o._statusCode, o.Payload)
}
func (o *GetPlanRevisionPracticeResponsesDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetPlanRevisionPracticeResponsesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
