// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListPracticesVersionsParams creates a new ListPracticesVersionsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListPracticesVersionsParams() *ListPracticesVersionsParams {
	return &ListPracticesVersionsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListPracticesVersionsParamsWithTimeout creates a new ListPracticesVersionsParams object
// with the ability to set a timeout on a request.
func NewListPracticesVersionsParamsWithTimeout(timeout time.Duration) *ListPracticesVersionsParams {
	return &ListPracticesVersionsParams{
		timeout: timeout,
	}
}

// NewListPracticesVersionsParamsWithContext creates a new ListPracticesVersionsParams object
// with the ability to set a context for a request.
func NewListPracticesVersionsParamsWithContext(ctx context.Context) *ListPracticesVersionsParams {
	return &ListPracticesVersionsParams{
		Context: ctx,
	}
}

// NewListPracticesVersionsParamsWithHTTPClient creates a new ListPracticesVersionsParams object
// with the ability to set a custom HTTPClient for a request.
func NewListPracticesVersionsParamsWithHTTPClient(client *http.Client) *ListPracticesVersionsParams {
	return &ListPracticesVersionsParams{
		HTTPClient: client,
	}
}

/* ListPracticesVersionsParams contains all the parameters to send to the API endpoint
   for the list practices versions operation.

   Typically these are written to a http.Request.
*/
type ListPracticesVersionsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list practices versions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListPracticesVersionsParams) WithDefaults() *ListPracticesVersionsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list practices versions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListPracticesVersionsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list practices versions params
func (o *ListPracticesVersionsParams) WithTimeout(timeout time.Duration) *ListPracticesVersionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list practices versions params
func (o *ListPracticesVersionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list practices versions params
func (o *ListPracticesVersionsParams) WithContext(ctx context.Context) *ListPracticesVersionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list practices versions params
func (o *ListPracticesVersionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list practices versions params
func (o *ListPracticesVersionsParams) WithHTTPClient(client *http.Client) *ListPracticesVersionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list practices versions params
func (o *ListPracticesVersionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ListPracticesVersionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
