// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ThalesGroup/besec/api/models"
)

// ListPracticesVersionsReader is a Reader for the ListPracticesVersions structure.
type ListPracticesVersionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListPracticesVersionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListPracticesVersionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewListPracticesVersionsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListPracticesVersionsOK creates a ListPracticesVersionsOK with default headers values
func NewListPracticesVersionsOK() *ListPracticesVersionsOK {
	return &ListPracticesVersionsOK{}
}

/* ListPracticesVersionsOK describes a response with status code 200, with default header values.

OK
*/
type ListPracticesVersionsOK struct {
	Payload []string
}

func (o *ListPracticesVersionsOK) Error() string {
	return fmt.Sprintf("[GET /practices][%d] listPracticesVersionsOK  %+v", 200, o.Payload)
}
func (o *ListPracticesVersionsOK) GetPayload() []string {
	return o.Payload
}

func (o *ListPracticesVersionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListPracticesVersionsDefault creates a ListPracticesVersionsDefault with default headers values
func NewListPracticesVersionsDefault(code int) *ListPracticesVersionsDefault {
	return &ListPracticesVersionsDefault{
		_statusCode: code,
	}
}

/* ListPracticesVersionsDefault describes a response with status code -1, with default header values.

error
*/
type ListPracticesVersionsDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the list practices versions default response
func (o *ListPracticesVersionsDefault) Code() int {
	return o._statusCode
}

func (o *ListPracticesVersionsDefault) Error() string {
	return fmt.Sprintf("[GET /practices][%d] listPracticesVersions default  %+v", o._statusCode, o.Payload)
}
func (o *ListPracticesVersionsDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *ListPracticesVersionsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
