// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewLoggedInParams creates a new LoggedInParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewLoggedInParams() *LoggedInParams {
	return &LoggedInParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewLoggedInParamsWithTimeout creates a new LoggedInParams object
// with the ability to set a timeout on a request.
func NewLoggedInParamsWithTimeout(timeout time.Duration) *LoggedInParams {
	return &LoggedInParams{
		timeout: timeout,
	}
}

// NewLoggedInParamsWithContext creates a new LoggedInParams object
// with the ability to set a context for a request.
func NewLoggedInParamsWithContext(ctx context.Context) *LoggedInParams {
	return &LoggedInParams{
		Context: ctx,
	}
}

// NewLoggedInParamsWithHTTPClient creates a new LoggedInParams object
// with the ability to set a custom HTTPClient for a request.
func NewLoggedInParamsWithHTTPClient(client *http.Client) *LoggedInParams {
	return &LoggedInParams{
		HTTPClient: client,
	}
}

/* LoggedInParams contains all the parameters to send to the API endpoint
   for the logged in operation.

   Typically these are written to a http.Request.
*/
type LoggedInParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the logged in params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *LoggedInParams) WithDefaults() *LoggedInParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the logged in params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *LoggedInParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the logged in params
func (o *LoggedInParams) WithTimeout(timeout time.Duration) *LoggedInParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the logged in params
func (o *LoggedInParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the logged in params
func (o *LoggedInParams) WithContext(ctx context.Context) *LoggedInParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the logged in params
func (o *LoggedInParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the logged in params
func (o *LoggedInParams) WithHTTPClient(client *http.Client) *LoggedInParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the logged in params
func (o *LoggedInParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *LoggedInParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
