// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/ThalesGroup/besec/lib"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GotPractices got practices
//
// swagger:model gotPractices
type GotPractices struct {

	// The practices indexed by their ID
	// Required: true
	Practices map[string]lib.Practice `json:"practices"`

	// version
	// Required: true
	Version *string `json:"version"`
}

// Validate validates this got practices
func (m *GotPractices) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePractices(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVersion(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GotPractices) validatePractices(formats strfmt.Registry) error {

	if err := validate.Required("practices", "body", m.Practices); err != nil {
		return err
	}

	for k := range m.Practices {

		if err := validate.Required("practices"+"."+k, "body", m.Practices[k]); err != nil {
			return err
		}
		if val, ok := m.Practices[k]; ok {
			if err := val.Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("practices" + "." + k)
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("practices" + "." + k)
				}
				return err
			}
		}

	}

	return nil
}

func (m *GotPractices) validateVersion(formats strfmt.Registry) error {

	if err := validate.Required("version", "body", m.Version); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this got practices based on the context it is used
func (m *GotPractices) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidatePractices(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GotPractices) contextValidatePractices(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.Required("practices", "body", m.Practices); err != nil {
		return err
	}

	for k := range m.Practices {

		if val, ok := m.Practices[k]; ok {
			if err := val.ContextValidate(ctx, formats); err != nil {
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *GotPractices) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GotPractices) UnmarshalBinary(b []byte) error {
	var res GotPractices
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
