// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SamlProviderClaimsMap A mapping from SAML claims to fields used within the app. Presence indicates this provider is a SAML provider.
//
// swagger:model samlProviderClaimsMap
type SamlProviderClaimsMap struct {

	// department
	Department string `json:"department,omitempty"`

	// email
	// Required: true
	Email *string `json:"email"`

	// first name
	FirstName string `json:"firstName,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// picture URL
	PictureURL string `json:"pictureURL,omitempty"`

	// surname
	Surname string `json:"surname,omitempty"`
}

// Validate validates this saml provider claims map
func (m *SamlProviderClaimsMap) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEmail(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SamlProviderClaimsMap) validateEmail(formats strfmt.Registry) error {

	if err := validate.Required("email", "body", m.Email); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this saml provider claims map based on context it is used
func (m *SamlProviderClaimsMap) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SamlProviderClaimsMap) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SamlProviderClaimsMap) UnmarshalBinary(b []byte) error {
	var res SamlProviderClaimsMap
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
