// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SignInOptions Firebase signin options, original type defined at firebaseui.auth.Config['signInOptions']
//
// swagger:model signInOptions
type SignInOptions struct {

	// button color
	// Example: #5DBFD4
	ButtonColor string `json:"buttonColor,omitempty"`

	// icon Url
	IconURL string `json:"iconUrl,omitempty"`

	// User facing name for this option
	ProviderName string `json:"providerName,omitempty"`
}

// Validate validates this sign in options
func (m *SignInOptions) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this sign in options based on context it is used
func (m *SignInOptions) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SignInOptions) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SignInOptions) UnmarshalBinary(b []byte) error {
	var res SignInOptions
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
