name: Builder

on:
  push:
    paths:
      - "build.Dockerfile"
    branches:
      - "main"
  workflow_dispatch:

jobs:
  builder:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          token_format: access_token
          workload_identity_provider: "projects/387575162441/locations/global/workloadIdentityPools/github/providers/github"
          service_account: "pipeline@besec-project.iam.gserviceaccount.com"
          access_token_lifetime: "300s"

      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - id: build_push
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: build.Dockerfile
          push: true
          tags: gcr.io/besec-project/build:latest
